# This is a basic workflow to help you get started with Actions


name: CI

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      source:
        description: The environment the desired images are already in
        type: string
        required: false
      destination:
        description: The environment you are deploying to
        type: string
        required: false

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_from_record_table:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        INDIGO_IMAGE_TAG: "${{ inputs.source != 'None' &&  inputs.destination || '' }}"
        run: echo ${INDIGO_IMAGE_TAG}
